# Generated by Django 3.2.5 on 2022-01-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicalsOctavo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mms_id', models.TextField()),
                ('issn', models.TextField(blank=True, null=True)),
                ('library_name', models.CharField(max_length=50)),
                ('new_library', models.CharField(blank=True, max_length=10, null=True)),
                ('location_name', models.CharField(max_length=20)),
                ('new_location', models.CharField(blank=True, max_length=20, null=True)),
                ('classmark', models.CharField(blank=True, max_length=20, null=True)),
                ('new_per_number', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(max_length=250)),
                ('holdings_and_wants', models.CharField(max_length=500)),
                ('new_holdings', models.CharField(blank=True, max_length=500, null=True)),
                ('new_wants_and_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('labeled_on_shelf', models.BooleanField(default=False)),
                ('amended_on_alma', models.BooleanField(default=False)),
            ],
        ),
    ]
