# Generated by Django 3.2.5 on 2022-04-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicalsOctavo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mms_id', models.TextField(max_length=255)),
                ('issn', models.TextField(blank=True, max_length=255, null=True)),
                ('library_name', models.CharField(max_length=50)),
                ('new_library', models.CharField(blank=True, max_length=10, null=True)),
                ('location_name', models.CharField(max_length=20)),
                ('new_location', models.CharField(blank=True, max_length=30, null=True)),
                ('classmark', models.CharField(blank=True, max_length=20, null=True)),
                ('new_per_number', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(max_length=250)),
                ('holdings_and_wants', models.CharField(max_length=500)),
                ('new_holdings', models.CharField(blank=True, max_length=500, null=True)),
                ('new_wants_and_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('labeled_on_shelf', models.BooleanField(default=False)),
                ('amended_on_alma', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodicalsUKRRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_code', models.CharField(max_length=10)),
                ('cycle_name', models.CharField(max_length=10)),
                ('cycle_list_name', models.CharField(max_length=10)),
                ('UKRR_id', models.IntegerField()),
                ('issn', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(max_length=250)),
                ('offering', models.CharField(max_length=250)),
                ('supplements', models.CharField(blank=True, max_length=250, null=True)),
                ('gaps', models.CharField(blank=True, max_length=250, null=True)),
                ('shelf_space', models.CharField(blank=True, max_length=10, null=True)),
                ('scarcity', models.CharField(blank=True, max_length=10, null=True)),
                ('holding', models.CharField(blank=True, max_length=10, null=True)),
                ('overlap', models.CharField(blank=True, max_length=10, null=True)),
                ('bl_scarcity', models.CharField(blank=True, max_length=250, null=True)),
                ('bl_scarcity_date', models.CharField(blank=True, max_length=250, null=True)),
                ('ml_scarcity', models.CharField(blank=True, max_length=250, null=True)),
                ('ml_scarcity_date', models.CharField(blank=True, max_length=250, null=True)),
                ('bl_response', models.CharField(blank=True, max_length=250, null=True)),
                ('not_requested', models.CharField(blank=True, max_length=250, null=True)),
                ('holdings_requested', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_request', models.CharField(blank=True, max_length=250, null=True)),
                ('bl_return_ref', models.CharField(max_length=10)),
                ('bl_overlap', models.CharField(max_length=10)),
                ('retention_status', models.CharField(max_length=20)),
                ('transfer_to_bl', models.CharField(blank=True, max_length=250, null=True)),
                ('retain', models.CharField(blank=True, max_length=250, null=True)),
                ('dispose', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
