# Generated by Django 3.2.5 on 2022-04-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persDb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='classmark',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='location_name',
            field=models.CharField(max_length=30),
        ),
    ]
