# Generated by Django 3.2.5 on 2022-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persDb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicalsUKRRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_code', models.CharField(max_length=10)),
                ('cycle_name', models.CharField(max_length=10)),
                ('cycle_list_name', models.CharField(max_length=10)),
                ('UKRR_id', models.IntegerField()),
                ('issn_no_hyphen', models.CharField(blank=True, max_length=10, null=True)),
                ('issn', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(max_length=250)),
                ('offering', models.CharField(max_length=250)),
                ('supplements', models.CharField(blank=True, max_length=250, null=True)),
                ('gaps', models.CharField(blank=True, max_length=250, null=True)),
                ('shelf_space', models.CharField(blank=True, max_length=10, null=True)),
                ('scarcity', models.CharField(blank=True, max_length=10, null=True)),
                ('holding', models.CharField(blank=True, max_length=10, null=True)),
                ('overlap', models.CharField(blank=True, max_length=10, null=True)),
                ('bl_scarcity', models.CharField(blank=True, max_length=250, null=True)),
                ('bl_scarcity_date', models.CharField(blank=True, max_length=250, null=True)),
                ('ml_scarcity', models.CharField(blank=True, max_length=250, null=True)),
                ('ml_scarcity_date', models.CharField(blank=True, max_length=250, null=True)),
                ('bl_response', models.CharField(blank=True, max_length=250, null=True)),
                ('not_requested', models.CharField(blank=True, max_length=250, null=True)),
                ('holdings_requested', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_request', models.CharField(blank=True, max_length=250, null=True)),
                ('bl_return_ref', models.CharField(max_length=10)),
                ('bl_overlap', models.CharField(max_length=10)),
                ('retention_status', models.CharField(max_length=20)),
                ('transfer_to_bl', models.CharField(blank=True, max_length=250, null=True)),
                ('retain', models.CharField(blank=True, max_length=250, null=True)),
                ('dispose', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
