# Generated by Django 3.2.5 on 2022-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persDb', '0002_auto_20220407_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='new_library',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
