# Generated by Django 3.2.5 on 2022-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persDb', '0002_periodicalsukrrstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='amended_on_alma',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='labeled_on_shelf',
            field=models.BooleanField(),
        ),
    ]
