# Generated by Django 3.2.5 on 2022-04-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persDb', '0003_alter_periodicalsoctavo_new_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='new_per_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
