# Generated by Django 3.2.5 on 2022-04-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persDb', '0004_alter_periodicalsoctavo_new_per_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='classmark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='location_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='new_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
