# Generated by Django 3.2.5 on 2022-03-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persDb', '0004_auto_20220225_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodicalsukrrstatus',
            name='issn_no_hyphen',
        ),
    ]
