# Generated by Django 3.2.5 on 2022-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persDb', '0005_auto_20220407_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicalsoctavo',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
